### ISSUE TITLE
TaggableMananger changing name 

### ISSUE THREAD

**Issue by leesolway** [bennylope/django-taggit-labels#2]
The JavaScript only supports one attribute name for the tags manager (tags). The TaggableManager however can be assigned to any attribute name breaking the js. 

var inputs = $("input#id_tags")[0];

**Comment by bennylope** [comment]
To restate the problem (and I'm seeking correction here): you want to use the TaggableManager with a field but that field is not named `tags` and this causes a problem because the JavaScript is hard coded to look for an `input` field with `id` of `id_tags`.

If that's the crux of the problem I'd try using the [`attr` parameter for the widget](https://docs.djangoproject.com/en/1.7/ref/forms/widgets/#django.forms.Widget.attrs) to provide a custom `id` value of `id_tags` regardless of the field name in your own form/model class(es).

**Comment by leesolway** [comment]
I didn't explain myself very well, thanks for clearing it up. What you've interpreted is correct.
The problem with the suggested solution though is that it wouldn't work if multiple tag managers are used on a single model.

**Comment by leesolway** [comment]
#3

**Comment by bennylope** [comment]
Closed by #3
